name: Deploy CDK Stack

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

    - name: Deploy CDK stack
      run: npx cdk deploy --ci --force --require-approval never --context domain_name=${{ vars.DOMAIN_NAME }} --context subdomain=${{ vars.SUBDOMAIN }}